<div class="modal" data-backdrop="static" data-keyboard="false" style="z-index: 99000 !important; overflow: auto;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button"
                        class="close"
                        data-dismiss="modal"
                        ng-click="fechar('cancel')"
                        name="button">
                    <i class="glyphicon glyphicon-remove"></i>
                </button>
                <h4 class="modal-title">
                    Simulador de Mensalidade
                </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div alert-bootstrap></div>
                        <div loading-bootstrap></div>
                    </div>
                </div>

                <div class="container">
                    <div class="price-box">
                        <div class="row">
                            <div class="col-sm-6">
                                <form name="formSimulador" class="form-horizontal form-pricing" role="form">

                                    <div class="price-slider">
                                        <h4 class="great">Localidade</h4>
                                        <span>Onde você vive?</span>
                                        <div class="col-sm-12">
                                            <div class="form-group">
                                                <select class="form-control"
                                                        ng-model="formulario.id_unidade"
                                                        ng-options="unidade.id as unidade.nome for unidade in listUnidades"
                                                        ng-required="true"
                                                        id="unidade">
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="price-slider">
                                        <h4 class="great">Tipo de Empresa</h4>
                                        <span>Qual o tipo da sua empresa?</span>
                                        <div class="col-sm-12">
                                        <div class="form-group">
                                            <select class="form-control"
                                                    ng-model="formulario.id_tipo_empresa"
                                                    ng-required="true"
                                                    ng-options="tipoempresa.id as tipoempresa.nome for tipoempresa in listTiposEmpresas"
                                                    id="tipo_empresa">
                                            </select>
                                        </div>
                                        </div>

                                    </div>
                                    <div class="price-slider">
                                        <h4 class="great">Sócios</h4>
                                        <span>Quantos sócios?</span>
                                        <div class="col-sm-12">
                                        <div class="form-group">
                                            <input type="number"
                                                   name="socios"
                                                   pattern="[0-9]*"
                                                   class="form-control"
                                                   id="socio"
                                                   min="1"
                                                   max="20"
                                                   pattern="^[0-9]"
                                                   ng-required="true"
                                                   ng-model="formulario.socios"
                                                   ng-blur="listarFaturamentos(formulario)"/>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="price-slider">
                                        <h4 class="great">Funcionários</h4>
                                        <span>Quantos funcionários?</span>
                                        <div class="col-sm-12">
                                        <div class="form-group">
                                            <input type="number"
                                                   name="funcionarios"
                                                   class="form-control"
                                                   id="funcionarios"
                                                   min="0"
                                                   max="500"
                                                   ng-required="true"
                                                   ng-model="formulario.funcionarios"
                                                   ng-blur="listarFaturamentos(formulario)"/>
                                        </div>
                                        </div>
                                    </div>
                                    <div class="price-slider">
                                        <h4 class="great">Faturamento</h4>
                                        <span>Qual o faturamento mensal?</span>
                                        <div class="col-sm-12">
                                        <select class="form-control"
                                                ng-model="formulario.id_faturamento"
                                                ng-required="true"
                                                ng-options="faturamento.id as faturamento.nome for faturamento in listFaturamentos"
                                                id="faturamento">
                                        </select>
                                        </div>
                                    </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="price-form" style="height: 555px;">

                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <label for="amount_amirol" class="control-label">Mensalidade(R$): </label>
                                                <span class="help-text">Este é o valor da sua mensalidade</span>
                                            </div>
                                            <div class="col-sm-6">
                                                <!-- <p class="price lead" id="total"></p> -->
                                                <input class="price lead" name="totalprice"  type="text" id="total" disabled="disabled" style="min-width:170px;" value="{{mensalidade ? 'R$ '+mensalidade[0].valor : 'R$ 0,00'}}" />
                                            </div>
                                        </div>

                                    </div>
                                    <div style="margin-top:30px"></div>
                                    <hr class="style">

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <button type="button" class="btn btn-primary btn-lg btn-block" ng-disabled="formSimulador.$error.required" ng-click="calculaMensalidade(formulario)" class="btn btn-primary">
                                                Calcular
                                                <span class="glyphicon glyphicon-chevron-right"></span>
                                            </button>
                                        </div>
                                    </div>

                                </div>

                                </form>
                            </div>
                        </div>

                    </div>

                </div>


            </div>

            <div class="modal-footer">
                <button type="button"
                        class="btn btn-default"
                        ng-click="fechar('cancel')"
                        data-dismiss="modal">Fechar
                </button>
            </div>

        </div>
    </div>
</div>
