<?php
include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
load_template(TEMPLATEPATH . '/anps-framework/shortcodes.php');

add_shortcode('anps_cta', 'anps_cta_func');
add_shortcode('appointment', 'anps_appointment_func');
add_shortcode("blog", "anps_blog_func");
add_shortcode("recent_portfolio_slider", "anps_recent_portfolio_slider_func");
add_shortcode("recent_portfolio", "anps_recent_portfolio_func");
add_shortcode("portfolio", "anps_portfolio_func");
add_shortcode("image", "anps_image_func");
add_shortcode("team", "anps_team_func");
add_shortcode("recent_blog", "anps_recent_blog_func");
add_shortcode("progress", "anps_progress_func");
add_shortcode("counter", "anps_counter_func");
add_shortcode('newsletter','newsletter_widget_func');
add_shortcode("coming_soon", "anps_coming_soon_func");
add_shortcode("twitter", "anps_twitter_func");
add_shortcode( 'content_half', 'content_half_func' );
add_shortcode( 'content_third', 'content_third_func' );
add_shortcode( 'content_two_third', 'content_two_third_func' );
add_shortcode( 'content_quarter', 'content_quarter_func' );
add_shortcode( 'content_two_quarter', 'content_two_quarter_func' );
add_shortcode( 'content_three_quarter', 'content_three_quarter_func' );
add_shortcode( 'icon', 'icon_func' );
add_shortcode( 'quote', 'quote_func' );
add_shortcode( 'color', 'color_func' );
add_shortcode( 'vimeo', 'vimeo_func' );
add_shortcode( 'youtube', 'youtube_func' );
add_shortcode( 'button', 'button_func' );
add_shortcode( 'error_404', 'error_404_func' );
add_shortcode('alert', 'anps_alert_func');
add_shortcode("dropcaps", "anps_dropcaps_func");
if ( is_plugin_active( 'js_composer/js_composer.php' ) && function_exists('vc_add_shortcode_param')) {
    include_once 'vc_shortcodes.php';
} else {
    add_shortcode('google_maps', 'google_maps_func');
    add_shortcode('google_maps_item', 'anps_google_maps_item');
    add_shortcode('section', 'section_func');
    add_shortcode('vc_single_image', 'anps_vc_single_image');
    add_shortcode('layerslider_vc', 'anps_vc_layer_slider');
    add_shortcode('rev_slider_vc', 'anps_vc_rev_slider');
    add_shortcode('vc_row', 'vc_theme_rows');
    add_shortcode('vc_row_inner', 'vc_theme_rows_inner');
    add_shortcode('vc_column', 'vc_theme_columns');
    add_shortcode('vc_column_inner', 'vc_theme_columns');
    add_shortcode('vc_column_text', 'vc_column_text_func');
    add_shortcode('vc_tabs', 'vc_tabs_func');
    add_shortcode('logos', 'anps_logos_func');
    add_shortcode('logo', 'anps_logo_func');
    add_shortcode('anps_list', 'anps_list_func');
    add_shortcode('list_item', 'anps_list_item_func');
    add_shortcode('social_icons', 'anps_social_icons_func');
    add_shortcode('social_icon_item', 'anps_social_icon_item_func');
    add_shortcode('statement','statement_func');
    add_shortcode('tabs', 'tabs_func');
    add_shortcode('tab', 'tab_func');
    add_shortcode('accordion', 'accordion_func');
    add_shortcode('accordion_item', 'accordion_item_func');
    add_shortcode('contact_info', 'anps_contact_info_func');
    add_shortcode('contact_info_item', 'anps_contact_info_item_func');
    add_shortcode('faq', 'anps_faq_func');
    add_shortcode('faq_item', 'anps_faq_item_func');
    add_shortcode('pricing_table', 'anps_pricing_table_func');
    add_shortcode( 'pricing_table_item', 'anps_pricing_table_item_func' );
    add_shortcode('testimonials', 'anps_testimonials');
    add_shortcode('testimonial', 'anps_testimonial');
}
add_shortcode('table', 'anps_table_func');
add_shortcode('table_head', 'anps_table_thead_func');
add_shortcode('table_body', 'anps_table_tbody_func');
add_shortcode('table_foot', 'anps_table_tfoot_func');
add_shortcode('table_row', 'anps_table_row_func');
add_shortcode('table_cell', 'anps_table_td_func');
add_shortcode('table_heading_cell', 'anps_table_th_func');
add_shortcode('heading', 'anps_heading_func');
