<link rel="stylesheet" type="text/css"
      href="https://cdn.jsdelivr.net/npm/angular-wizard@latest/dist/angular-wizard.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<wizard on-finish="inscrever()" indicators-position="top">
    <br><br>
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div alert-bootstrap></div>
            <div loading-bootstrap></div>
        </div>
    </div>
    <wz-step wz-title="Dados Pessoais">
        <div class="col-sm-10 col-sm-offset-1">

            <form name="formDadosCliente"
                  method="post"
                  ng-submit="salvarCliente()"
                  autocomplete="off"
                  novalidate>


                <h5 class="page-header">Dados do Cliente</h5>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="nome">Nome Completo:(*)</label>
                        <input type="nome"
                               ng-model="formCliente.nome"
                               class="form-control"
                               id="nome"
                               placeholder="Nome"/>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="data_nascimento">Data de Nascimento:(*)</label>
                        <input id="data_nascimento"
                               ng-init="tratarData(formCliente)"
                               ng-model="formCliente.data_nascimento"
                               class="form-control"
                               type="text"
                               ui-date-mask="DD/MM/YYYY"
                               placeholder="Data de Nascimento"
                        />
                    </div>
                    <div class="form-group col-md-3">
                        <label for="genero">Gênero:(*)</label>
                        <select name="genero"
                                id="genero"
                                ng-model="formCliente.id_sexo"
                                ng-options="genero.id as genero.nome for genero in listaGeneros"
                                ng-required="true"
                                class="form-control">
                        </select>

                    </div>
                    <div class="form-group col-md-3">
                        <label for="sexo">Estado Civil:(*)</label>
                        <select name="sexo"
                                id="sexo"
                                ng-model="formCliente.id_estado_civil"
                                ng-options="estadocivil.id as estadocivil.nome for estadocivil in listaEstadosCivis"
                                ng-required="true"
                                class="form-control">
                        </select>
                    </div>
                </div>


                <h5 class="page-header">Documentos</h5>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="rg">CPF:(*)</label>
                        <input type="text"
                               ng-model="formCliente.cpf"
                               class="form-control"
                               id="cpf"
                               ng-cpf
                               ui-br-cpf-mask
                               ng-required="true"
                               placeholder="CPF"/>
                        <p ng-show="formCliente.cpf.$invalid && !formCliente.cpf.$pristine" class="help-block">O seu CPF está inválido!</p>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="rg">RG:(*)</label>
                        <input type="text"
                               ng-model="formCliente.rg"
                               class="form-control"
                               id="rg"
                               numeric-only
                               ng-required="true"
                               placeholder="RG"/>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="orgaoExpedidor">Órgão Emissor:(*)</label>
                        <input type="text"
                               ng-model="formCliente.orgao_rg"
                               class="form-control"
                               id="orgaoExpedidor"
                               ng-required="true"
                               placeholder="Órgão Expedidor"/>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="dataEmissao">Data de Emissão:(*)</label>
                        <input type="text"
                               ng-model="formCliente.data_emissao_rg"
                               class="form-control"
                               id="dataEmissao"
                               ng-required="true"
                               ui-date-mask="DD/MM/YYYY"
                               placeholder="Data de Emissão"/>
                    </div>
                </div>
                <h5 class="page-header">Endereço</h5>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="cep">CEP:(*)</label>
                        <input type="text"
                               ng-model="formCliente.cep"
                               class="form-control"
                               id="cep"
                               ng-required="true"
                               ng-blur="buscarCep(formCliente)"
                               placeholder="CEP"/>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="rua">Rua:(*)</label>
                        <input type="text"
                               ng-model="formCliente.rua"
                               class="form-control"
                               id="rua"
                               ng-required="true"
                               placeholder="Rua"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="numero">Número:(*)</label>
                        <input type="text"
                               ng-model="formCliente.numero"
                               class="form-control"
                               id="numero"
                               ng-required="true"
                               placeholder="Número"/>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="complemento">Complemento:(*)</label>
                        <input type="text"
                               ng-model="formCliente.complemento"
                               class="form-control"
                               id="complemento"
                               ng-required="true"
                               placeholder="Complemento"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="bairro">Bairro:</label>
                        <input type="text"
                               ng-model="formCliente.bairro"
                               class="form-control"
                               id="bairro"
                               placeholder="Bairro"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="cidade">Cidade:(*)</label>
                        <input type="text"
                               ng-model="formCliente.cidade"
                               class="form-control"
                               id="cidade"
                               ng-required="true"
                               placeholder="Cidade"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="estado">Estado:</label>
                        <input type="text"
                               ng-model="formCliente.estado"
                               class="form-control"
                               id="estado"
                               placeholder="Estado"/>
                    </div>
                </div>

                <h5 class="page-header">Contato</h5>
                <div class="row">
                    <div class="form-group col-md-2">
                        <label for="ddd">DDD:</label>
                        <input type="text"
                               ng-model="formCliente.ddd"
                               class="form-control"
                               id="ddd"
                               placeholder="DDD"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="telefoneResidencial">Telefone Residencial:</label>
                        <input type="text"
                               ng-model="formCliente.telefone_residencial"
                               class="form-control"
                               id="telefoneResidencial"
                               placeholder="Telefone Residencial"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="telefoneCelular">Telefone Celular:(*)</label>
                        <input type="text"
                               ng-blur="tratarData(formCliente)"
                               ng-model="formCliente.telefone_celular"
                               class="form-control"
                               id="telefoneCelular"
                               ng-required="true"
                               placeholder="Telefone Celular"/>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="email">E-mail:(*)</label>
                        <input type="email"
                               ng-model="formCliente.email"
                               class="form-control"
                               id="email"
                               ng-required="true"
                               placeholder="Email"/>
                    </div>
                </div>
                <h5 class="page-header">Usuário</h5>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="senha">Senha:(*)</label>
                        <input type="password"
                               ng-model="formCliente.senha"
                               class="form-control"
                               id="senha"
                               ng-required="true"
                               placeholder="Senha"/>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="confirma_senha">Confirma Senha:(*)</label>
                        <input type="password"
                               ng-model="formCliente.confirma_senha"
                               class="form-control"
                               id="confirma_senha"
                               ng-required="true"
                               placeholder="Confirma Senha"/>
                    </div>
                </div>


                <div class="form-group col-sm-12 text-center">
                    <button class="btn btn-success btn-sm"
                            type="submit"
                            ng-disabled="formDadosCliente.$error.required || formDadosCliente.$invalid ">
                        Avançar
                    </button>

                    <button class="btn btn-danger waves-effect btn-sm"
                            ng-if="autenticado==true"
                            ng-click="sair()"
                            type="submit">
                        Sair
                    </button>
<!--
                    <button class="btn btn-success btn-sm"
                            type="button"
                            ng-click="getBandeiraCartao('4111111111111111')"
                    >
                        Cartão
                    </button>
                    -->
                </div>

            </form>
        </div>
    </wz-step>
    <wz-step wz-title="Contratação">
        <div class="col-sm-10 col-sm-offset-1">
            <form name="formDadosContrato"
                  method="post"
                  autocomplete="off"
                  ng-submit="salvarContrato(formContrato)"
                  novalidate>
                <input type="hidden" name="id_cliente" ng-model="formContrato.id_cliente"
                       ng-value="formContrato.id_cliente = id_cliente"/>
                <h5 class="page-header">Plano para Contratação</h5>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="unidade">Sua Localidade:</label>
                        <select class="form-control"
                                ng-model="formContrato.id_unidade"
                                ng-options="unidade.id as unidade.nome for unidade in listUnidades"
                                ng-required="true"
                                id="unidade">
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="tipo_empresa">Tipo de Empresa:</label>
                        <select class="form-control"
                                ng-model="formContrato.id_tipo_empresa"
                                ng-required="true"
                                ng-options="tipoempresa.id as tipoempresa.nome for tipoempresa in listTiposEmpresas"
                                id="tipo_empresa">
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="socios">Número de Sócios:</label>
                        <input type="number"
                               name="socios"
                               pattern="[0-9]*"
                               class="form-control"
                               id="socios"
                               min="1"
                               max="20"
                               pattern="^[0-9]"
                               ng-required="true"
                               ng-model="formContrato.socios"
                               ng-blur="listarFaturamentos(formContrato)"/>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="funcionarios">Número de Funcionários:</label>
                        <input type="number"
                               name="funcionarios"
                               class="form-control"
                               id="funcionarios"
                               min="0"
                               max="500"
                               ng-required="true"
                               ng-model="formContrato.funcionarios"
                               ng-blur="listarFaturamentos(formContrato)"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="faturamento">Faturamento Mensal:</label>
                        <select class="form-control"
                                ng-model="formContrato.id_faturamento"
                                ng-required="true"
                                ng-options="faturamento.id as faturamento.nome for faturamento in listFaturamentos"
                                ng-change="calculaMensalidade(formContrato)"
                                id="faturamento">
                        </select>
                    </div>
                    <input type="hidden" name="id_mensalidade" ng-model="formContrato.id_mensalidade"
                           ng-value="formContrato.id_mensalidade = mensalidade[0].id"/>
                </div>

                <div class="col-sm-12 text-center" ng-if="mensalidade">
                    <label>Valor Pago: {{mensalidade ? 'R$ '+mensalidade[0].mensalidade : 'R$ 0,00'}}</label>
                    <label>Cliente: {{id_cliente}}</label>
                    <label>Plano: {{mensalidade[0].id}}</label>
                </div>

                <div class="form-group col-sm-12 text-center">

                    <button class="btn btn-danger waves-effect btn-sm"
                            type="button"
                            wz-previous>
                        Voltar
                    </button>

                    <button class="btn btn-info waves-effect btn-sm"
                            type="submit"
                            ng-disabled="formDadosContrato.$error.required">
                        Avançar
                    </button>

                </div>

            </form>
        </div>
    </wz-step>

    <wz-step wz-title="Pagamento">
        <div class="col-sm-10 col-sm-offset-1">

           <!-- <a href="" class="btn btn-primary btn-lg" ng-click="habilitaCartao()">Cartão de Crédito</a>-->
            <!--<a href="" class="btn btn-default btn-lg" ng-click="habilitaBoleto()">Boleto Bancário</a>-->

            <form name="formDadosAssinatura" method="post" ng-submit="assinarCartao(formAssinatura)">
                <div class="form-group">
                    <label for="numero_cartao">Número do Cartão:(*)</label>
                    <input type="text"
                           ng-model="formAssinatura.numero"
                           class="form-control"
                           id="numero_cartao"
                           ng-required="true"
                           placeholder="Número do Cartão"/>
                </div>
                <div class="form-group">
                    <label for="cvv">CVV:(*)</label>
                    <input type="text"
                           ng-model="formAssinatura.cvv"
                           class="form-control"
                           id="cvv"
                           ng-required="true"
                           placeholder="CVV"/>
                </div>
                <div class="form-group">
                    <label for="mes_expiracao">Mês de Expiração:(*)</label>
                    <input type="text"
                           ng-model="formAssinatura.mes_expiracao"
                           class="form-control"
                           id="mes_expiracao"
                           ng-required="true"
                           placeholder="Mês de Expiração"/>
                </div>
                <div class="form-group">
                    <label for="ano_expiracao">Ano de Expiração:(*)</label>
                    <input type="text"
                           ng-model="formAssinatura.ano_expiracao"
                           class="form-control"
                           id="ano_expiracao"
                           ng-required="true"
                           placeholder="Ano de Expiração"/>
                </div>

                <div class="form-group col-sm-12 text-center">

                    <button class="btn btn-danger waves-effect btn-sm"
                            type="button"
                            wz-previous>
                        Voltar
                    </button>

                    <button class="btn btn-info waves-effect btn-sm"
                            type="submit"
                            ng-disabled="formDadosAssinatura.$error.required">
                        Realizar Pagamento
                    </button>

                </div>
            </form>
            <div ng-if="boleto==true">
                <form name="formDadosAssinatura" method="post" ng-submit="gerarBoletos(formAssinatura)">
                <button class="btn btn-info waves-effect btn-sm"
                        type="submit">
                    Gerar Boletos
                </button>
                </form>

            </div>


        </div>
    </wz-step>

    <wz-step wz-title="Finalização">
        <div class="col-sm-10 col-sm-offset-1">
            <div class="alert alert-info" role="alert">
                O seu pagamento está sendo processado pelo PagSeguro. Você irá receber no seu e-mail, uma notificação de pagamento. Você pode consultar o status da sua transação acessando a área do cliente no nosso site. Obrigado por escolher a RSC Contabilidade.
            </div>
        </div>
    </wz-step>
</wizard>