<link rel="stylesheet" type="text/css"
      href="https://cdn.jsdelivr.net/npm/angular-wizard@latest/dist/angular-wizard.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<wizard on-finish="inscrever()" indicators-position="top">
    <br><br>
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div alert-bootstrap></div>
            <div loading-bootstrap></div>
        </div>
    </div>

    <wz-step wz-title="Dados Pessoais">

        <div class="col-sm-10 col-sm-offset-1">
            <form name="formDadosCliente"
                  method="post"
                  ng-submit="salvarCliente()"
                  autocomplete="off"
                  novalidate>

                <h4>Dados do Cliente</h4>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="nome">Nome Completo:(*)</label>
                        <input type="nome"
                               ng-model="formCliente.nome"
                               class="form-control"
                               id="nome"
                               placeholder="Nome"/>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="data_nascimento">Data de Nascimento:(*)</label>
                        <input id="data_nascimento"
                               ng-init="tratarData(formCliente)"
                               ng-model="formCliente.data_nascimento"
                               class="form-control"
                               type="text"
                               ui-date-mask="DD/MM/YYYY"
                               placeholder="Data de Nascimento"
                        />
                    </div>
                    <div class="form-group col-md-3">
                        <label for="genero">Gênero:(*)</label>
                        <select name="genero"
                                id="genero"
                                ng-model="formCliente.id_sexo"
                                ng-options="genero.id as genero.nome for genero in listaGeneros"
                                ng-required="true"
                                class="form-control">
                        </select>

                    </div>
                    <div class="form-group col-md-3">
                        <label for="sexo">Estado Civil:(*)</label>
                        <select name="sexo"
                                id="sexo"
                                ng-model="formCliente.id_estado_civil"
                                ng-options="estadocivil.id as estadocivil.nome for estadocivil in listaEstadosCivis"
                                ng-required="true"
                                class="form-control">
                        </select>
                    </div>
                </div>


                <h5 class="page-header">Documentos</h5>
                <div class="row">


                <div class="radio-inline">
                    <label>
                        <input type="radio" ng-model="formCliente.id_tipo_pessoa" ng-required="!formCliente.id_tipo_pessoa" ng-value="1" name="tipo" ng-change="selecionaPessoa('fisica')">Pessoa Física
                    </label>
                </div>
                <div class="radio-inline">
                    <label>
                        <input type="radio" ng-model="formCliente.id_tipo_pessoa" ng-required="!formCliente.id_tipo_pessoa" ng-value="2" name="tipo" ng-change="selecionaPessoa('juridica')">Pessoa Jurídica
                    </label>
                </div>
                </div>
                <div class="row">

                    <div class="form-group col-md-3" ng-if="fisica==true">
                        <label for="rg">CPF:(*)</label>
                        <input type="text"
                               ng-model="formCliente.cpf_cnpj"
                               name="cpf_cnpj"
                               class="form-control"
                               id="cpf_cnpj"
                               ng-cpf
                               ui-br-cpf-mask
                               ng-required="true"
                               placeholder="CPF"/>
                        <p style="color:red" ng-show ="formDadosCliente.cpf_cnpj.$invalid && !formDadosCliente.cpf_cnpj.$pristine">O seu CPF está inválido!</p>
                    </div>
                    <div class="form-group col-md-3" ng-if="fisica==false">
                        <label for="cpf_cnpj">CNPJ:(*)</label>
                        <input type="text"
                               ng-model="formCliente.cpf_cnpj"
                               name="cpf_cnpj"
                               class="form-control"
                               id="cpf_cnpj"
                               ng-cnpj
                               ui-br-cnpj-mask
                               ng-required="true"
                               placeholder="CNPJ"/>
                        <p style="color:red" ng-show ="formDadosCliente.cpf_cnpj.$invalid && !formDadosCliente.cpf_cnpj.$pristine">O seu CNPJ está inválido!</p>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="rg">RG:(*)</label>
                        <input type="text"
                               name="rg"
                               ng-model="formCliente.rg"
                               class="form-control"
                               id="rg"
                               numeric-only
                               ng-required="true"
                               placeholder="RG"/>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="orgaoExpedidor">Órgão Emissor:(*)</label>
                        <input type="text"
                               ng-model="formCliente.orgao_rg"
                               class="form-control"
                               id="orgaoExpedidor"
                               ng-required="true"
                               placeholder="Órgão Expedidor"/>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="dataEmissao">Data de Emissão:(*)</label>
                        <input type="text"
                               ng-model="formCliente.data_emissao_rg"
                               class="form-control"
                               id="dataEmissao"
                               ng-required="true"
                               ui-date-mask="DD/MM/YYYY"
                               placeholder="Data de Emissão"/>
                    </div>
                </div>
                <h5 class="page-header">Endereço</h5>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="cep">CEP:(*)</label>
                        <input type="text"
                               name="cep"
                               ng-model="formCliente.cep"
                               class="form-control"
                               id="cep"
                               ng-required="true"
                               ng-blur="buscarCep(formCliente)"
                               numeric-only
                               placeholder="CEP"/>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="rua">Rua:(*)</label>
                        <input type="text"
                               ng-model="formCliente.rua"
                               class="form-control"
                               id="rua"
                               ng-required="true"
                               placeholder="Rua"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="numero">Número:(*)</label>
                        <input type="text"
                               ng-model="formCliente.numero"
                               class="form-control"
                               id="numero"
                               ng-required="true"
                               placeholder="Número"/>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="complemento">Complemento:(*)</label>
                        <input type="text"
                               ng-model="formCliente.complemento"
                               class="form-control"
                               id="complemento"
                               ng-required="true"
                               placeholder="Complemento"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="bairro">Bairro:</label>
                        <input type="text"
                               ng-model="formCliente.bairro"
                               class="form-control"
                               id="bairro"
                               placeholder="Bairro"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="cidade">Cidade:(*)</label>
                        <input type="text"
                               ng-model="formCliente.cidade"
                               class="form-control"
                               id="cidade"
                               ng-required="true"
                               placeholder="Cidade"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="estado">Estado:</label>
                        <input type="text"
                               ng-model="formCliente.estado"
                               class="form-control"
                               id="estado"
                               placeholder="Estado"/>
                    </div>
                </div>

                <h5 class="page-header">Contato</h5>
                <div class="row">
                    <div class="form-group col-md-2">
                        <label for="ddd">DDD:</label>
                        <input type="text"
                               name="ddd"
                               ng-model="formCliente.ddd"
                               class="form-control"
                               id="ddd"
                               numeric-only
                               ui-mask="99"
                               ui-mask-placeholder
                               placeholder="DDD"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="telefoneResidencial">Telefone Residencial:</label>
                        <input type="text"
                               name="telefone_residencial"
                               ng-model="formCliente.telefone_residencial"
                               class="form-control"
                               id="telefoneResidencial"
                               numeric-only
                               ui-mask="99999999"
                               ui-mask-placeholder
                               placeholder="Telefone Residencial"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="telefoneCelular">Telefone Celular:(*)</label>
                        <input type="text"
                               name="telefone_celular"
                               ng-blur="tratarData(formCliente)"
                               ng-model="formCliente.telefone_celular"
                               class="form-control"
                               id="telefoneCelular"
                               ng-required="true"
                               numeric-only
                               ui-mask="999999999"
                               ui-mask-placeholder
                               placeholder="Telefone Celular"/>
                    </div>

                    <div class="form-group col-md-4">
                        <label for="email">E-mail:(*)</label>
                        <input type="email"
                               name="email"
                               ng-model="formCliente.email"
                               class="form-control"
                               id="email"
                               ng-required="true"
                               placeholder="Email"/>
                        <span style="color:red" ng-show="formDadosCliente.email.$error.email && formDadosCliente.email.$dirty">Endereço de E-Mail inválido.</span>
                    </div>
                </div>
                <h5 class="page-header">Usuário</h5>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="senha">Senha:(*)</label>
                        <input type="password"
                               name="senha"
                               ng-model="formCliente.senha"
                               class="form-control"
                               id="senha"
                               ng-required="true"
                               placeholder="Senha"/>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="confirma_senha">Confirma Senha:(*)</label>
                        <input type="password"
                               name="confirma_senha"
                               ng-model="formCliente.confirma_senha"
                               class="form-control"
                               id="confirma_senha"
                               ng-required="true"
                               match-password="formCliente.senha"
                               placeholder="Confirma Senha"/>
                        <div ng-if="formDadosCliente.confirma_senha.$touched">
                            <p style="color:red" ng-show="formDadosCliente.confirma_senha.$error.matchPassword && !formDadosCliente.confirma_senha.$error.required">As senhas não coincidem</p>
                        </div>
                    </div>
                </div>


                <div class="form-group col-sm-12 text-center">
                    <button class="btn btn-success btn-sm"
                            type="submit"
                            ng-disabled="formDadosCliente.$error.required || formDadosCliente.$invalid ">
                        Avançar
                    </button>

                    <button class="btn btn-danger waves-effect btn-sm"
                            ng-if="autenticado==true"
                            ng-click="sair()"
                            type="submit">
                        Sair
                    </button>
<!--
                    <button class="btn btn-success btn-sm"
                            type="button"
                            ng-click="getBandeiraCartao('4111111111111111')"
                    >
                        Cartão
                    </button>
                    -->
                </div>

            </form>
        </div>
    </wz-step>
    <wz-step wz-title="Contratação">
        <div class="col-sm-10 col-sm-offset-1">
            <form name="formDadosContrato"
                  method="post"
                  autocomplete="off"
                  ng-submit="salvarContrato(formContrato)"
                  novalidate>
                <input type="hidden" name="id_cliente" ng-model="formContrato.id_cliente"
                       ng-value="formContrato.id_cliente = id_cliente"/>
                <h5 class="page-header">Plano para Contratação</h5>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label for="unidade">Sua Localidade:</label>
                        <select class="form-control"
                                ng-model="formContrato.id_unidade"
                                ng-options="unidade.id as unidade.nome for unidade in listUnidades"
                                ng-required="true"
                                id="unidade">
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="tipo_empresa">Tipo de Empresa:</label>
                        <select class="form-control"
                                ng-model="formContrato.id_tipo_empresa"
                                ng-required="true"
                                ng-options="tipoempresa.id as tipoempresa.nome for tipoempresa in listTiposEmpresas"
                                id="tipo_empresa">
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="socios">Número de Sócios:</label>
                        <input type="number"
                               name="socios"
                               pattern="[0-9]*"
                               class="form-control"
                               id="socios"
                               min="1"
                               max="20"
                               pattern="^[0-9]"
                               ng-required="true"
                               ng-model="formContrato.socios"
                               ng-blur="listarFaturamentos(formContrato)"/>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="funcionarios">Número de Funcionários:</label>
                        <input type="number"
                               name="funcionarios"
                               class="form-control"
                               id="funcionarios"
                               min="0"
                               max="500"
                               ng-required="true"
                               ng-model="formContrato.funcionarios"
                               ng-blur="listarFaturamentos(formContrato)"/>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="faturamento">Faturamento Mensal:</label>
                        <select class="form-control"
                                ng-model="formContrato.id_faturamento"
                                ng-required="true"
                                ng-options="faturamento.id as faturamento.nome for faturamento in listFaturamentos"
                                ng-change="calculaMensalidade(formContrato)"
                                id="faturamento">
                        </select>
                    </div>
                    <input type="hidden" name="id_mensalidade" ng-model="formContrato.id_mensalidade"
                           ng-value="formContrato.id_plano = mensalidade[0].id"/>
                </div>

                <div class="row" ng-if="mensalidade">
                    <div class="text-center">
                        <h1>Assinatura</h1>
                    </div>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Plano</th>
                            <th class="text-center">Preço</th>
                            <th class="text-center">Total</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td class="col-md-9"><em>{{mensalidade[0].tipo_empresa}}</em></td>
                            <td class="col-md-1 text-center">{{mensalidade ? 'R$ '+mensalidade[0].valor : 'R$ 0,00'}}</td>
                            <td class="col-md-1 text-center">{{mensalidade ? 'R$ '+mensalidade[0].valor : 'R$ 0,00'}}</td>
                        </tr>
                        <tr>
                            <td>   </td>
                            <td class="text-right">
                                <p>
                                    <strong>Subtotal: </strong>
                                </p>
                                <p>
                                    <strong>Taxa: </strong>
                                </p></td>
                            <td class="text-center">
                                <p>
                                    <strong>{{subTotal ? 'R$ '+subTotal : 'R$ 0,00'}}</strong>
                                </p>
                                <p>
                                    <strong>R$ 0,00</strong>
                                </p></td>
                        </tr>
                        <tr>
                            <td>   </td>
                            <td class="text-right"><h4><strong>Total: </strong></h4></td>
                            <td class="text-center text-danger"><h4><strong>{{valorTotal ? 'R$ '+valorTotal : 'R$ 0,00'}}</strong></h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <div class="form-group col-sm-12 text-center">

                    <button class="btn btn-danger waves-effect btn-sm"
                            type="button"
                            wz-previous>
                        Voltar
                    </button>

                    <button class="btn btn-info waves-effect btn-sm"
                            type="submit"
                            ng-disabled="formDadosContrato.$error.required">
                        Avançar
                    </button>

                </div>

            </form>
        </div>
    </wz-step>

    <wz-step wz-title="Pagamento">
        <div class="col-sm-10 col-sm-offset-1">

            <a href="" class="btn btn-primary btn-lg" ng-click="habilitaCartao()">Cartão de Crédito</a>
            <a href="" class="btn btn-default btn-lg" ng-click="habilitaBoleto()">Boleto Bancário</a>
            <br><br><br>
            <div class="container" ng-if="cartao==true">
                <div class="row">
                    <!-- You can make it whatever width you want. I'm making it full width
                    on <= small devices and 4/12 page width on >= medium devices -->
                    <div class="col-xs-12 col-md-5">
                        <!-- CREDIT CARD FORM STARTS HERE -->
                        <div class="panel panel-default credit-card-box">
                            <div class="panel-heading display-table" >
                                <div class="row display-tr" >
                                    <h3 class="panel-title display-td" >Cartão de Crédito</h3>
                                    <div class="display-td" >
                                        <img class="img-responsive pull-right" src="//i76.imgup.net/accepted_c22e0.png">
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <form name="formDadosAssinatura" method="post" ng-submit="assinarCartao(formAssinatura)" role="form" id="payment-form">
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <div class="form-group">
                                                <label for="numero_cartao">Número de Cartão</label>
                                                <div class="input-group">
                                                    <input
                                                            type="text"
                                                            name="numero_cartao"
                                                            class="form-control"
                                                            ng-model="formAssinatura.numero_cartao"
                                                            placeholder="Número de Cartão"
                                                            autocomplete="cc-number"
                                                            required autofocus
                                                    />
                                                    <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-7 col-md-7">
                                            <div class="form-group">
                                                <label for="expiracao"><span class="hidden-xs">Expiração</span><span class="visible-xs-inline">EXP</span> Data</label>
                                                <input
                                                        type="text"
                                                        class="form-control"
                                                        ng-model="formAssinatura.expiracao"
                                                        name="expiracao"
                                                        placeholder="MM/YYYY"
                                                        ui-mask="99/9999"
                                                        ui-mask-placeholder
                                                        autocomplete="cc-exp"
                                                        required
                                                />
                                            </div>
                                        </div>
                                        <div class="col-xs-5 col-md-5 pull-right">
                                            <div class="form-group">
                                                <label for="cvv">CVV</label>
                                                <input
                                                        type="text"
                                                        class="form-control"
                                                        name="cvv"
                                                        ng-model="formAssinatura.cvv"
                                                        placeholder="CVV"
                                                        autocomplete="cc-csc"
                                                        required
                                                />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-12">
                                            <button class="btn btn-success btn-sm waves-effect" type="submit">Pagar</button>
                                            <button class="btn btn-danger waves-effect btn-sm"
                                                    type="button"
                                                    wz-previous>
                                                Voltar
                                            </button>
                                        </div>

                                    </div>
                                    <div class="row" style="display:none;">
                                        <div class="col-xs-12">
                                            <p class="payment-errors"></p>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- CREDIT CARD FORM ENDS HERE -->


                    </div>

                </div>
            </div>

            <div ng-if="boleto==true">
                <form name="formDadosAssinatura" method="post" ng-submit="gerarBoletos(formAssinatura)">
                    <button class="btn btn-info waves-effect btn-sm"
                            type="submit">
                        Avançar
                    </button>
                </form>

            </div>


        </div>
    </wz-step>

    <wz-step wz-title="Finalização">
        <div class="col-sm-10 col-sm-offset-1" ng-if="cartao==true">
            <div class="alert alert-info" role="alert">
                O seu pagamento está sendo processado pelo PagSeguro. Você irá receber no seu e-mail, uma notificação de pagamento. Você pode consultar o status da sua transação acessando a área do cliente no nosso site. Obrigado por escolher a RSC Contabilidade.
            </div>
        </div>
        <div class="col-sm-10 col-sm-offset-1" ng-if="boleto==true">
            <div class="alert alert-info" role="alert">
                O seu carnê de boletos foi gerado com sucesso. Você poderá visualizá-los na área do cliente no site. Obrigado por escolher a RSC Contabilidade.
            </div>
        </div>
    </wz-step>
</wizard>