<div class="modal" data-backdrop="static" data-keyboard="false" style="z-index: 99000 !important">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button"
                        class="close"
                        data-dismiss="modal"
                        ng-click="fechar('cancel')"
                        name="button">
                    <i class="glyphicon glyphicon-remove"></i>
                </button>
                <h4 class="modal-title">
                    Cálculo de Mensalidade
                </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div alert-bootstrap></div>
                        <div loading-bootstrap></div>
                    </div>
                </div>

                <form name="formMensalidade" role="form">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <div class="form-group col-md-4">
                                <label for="unidade">Onde você vive?</label>
                                <select class="form-control"
                                        ng-model="formulario.id_unidade"
                                        ng-options="unidade.id as unidade.nome for unidade in listUnidades"
                                        ng-required="true"
                                        id="unidade">
                                </select>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="tipo_empresa">Qual o tipo de empresa?</label>
                                <select class="form-control"
                                        ng-model="formulario.id_tipo_empresa"
                                        ng-required="true"
                                        ng-options="tipoempresa.id as tipoempresa.nome for tipoempresa in listTiposEmpresas"
                                        id="tipo_empresa">
                                </select>
                            </div>

                            <div class="form-group col-md-4">
                                <label for="socios">Quantos sócios?</label>
                                <input type="number"
                                       name="socios"
                                       pattern="[0-9]*"
                                       class="form-control"
                                       id="socio"
                                       min="1"
                                       max="20"
                                       ng-required="true"
                                       ng-model="formulario.socios"/>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="funcionarios">Quantos funcionários?</label>
                                <input type="number"
                                       name="funcionarios"
                                       class="form-control"
                                       id="funcionarios"
                                       value="42"
                                       ng-min="0"
                                       ng-max="500"
                                       ng-required="true"
                                       ng-model="formulario.funcionarios"
                                       />
                                <button type="button" ng-click="listarFaturamentos(formulario)" class="btn btn-primary">
                                    Calcular
                                </button>
                            </div>
                            <div class="form-group col-md-4">
                                <label for="faturamento">Qual o seu faturamento mensal?</label>
                                <select class="form-control"
                                        ng-model="formulario.id_faturamento"
                                        ng-required="true"
                                        ng-options="faturamento.id as faturamento.nome for faturamento in listFaturamentos"
                                        id="faturamento">
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group col-md-4">
                                <button type="button" ng-disabled="formMensalidade.$error.required" ng-click="calculaMensalidade(formulario)" class="btn btn-primary">
                                    Calcular
                                </button>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-success col-md-4" ng-if="mensalidade" role="alert">
                                <label>Sua mensalidade será:</label>
                                <h1>R$ {{mensalidade[0].mensalidade}}/mês</h1>
                            </div>
                        </div>
                    </div>
                </form>

            </div>

            <div class="modal-footer">
                <button type="button"
                        class="btn btn-default"
                        ng-click="fechar('cancel')"
                        data-dismiss="modal">Fechar
                </button>
            </div>

        </div>
    </div>
</div>
