<?php
if (!defined('ABSPATH') || !$this instanceof \MocaBonita\view\MbView) :
    die("Você não tem permissão para acessar este arquivo!");
endif;
?>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Área do Cliente</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Dados Pessoais</a></li>
            <li><a href="#">Pagamentos</a></li>
            <li><a href="#">Documentos</a></li>
            <li><a href="#">Plano</a></li>
        </ul>
    </div>
</nav>