<div class="col-sm-12" ng-controller="documentoClienteController" ng-cloak>
<h4>Clientes</h4>
        <table class="table table-hover" ng-if="listaClientes.length">
            <thead>
            <tr>
                <th class="text-center">Nome</th>
                <th class="text-center">CPF/CNPJ</th>
                <th class="text-center">Plano</th>
                <th class="text-center">Documentos</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="cliente in listaClientes">
                <td class="text-center">{{cliente.nome}}</td>
                <td class="text-center">{{cliente.cpf_cnpj}}</td>
                <td class="text-center">{{cliente.tipo_empresa+' - '+cliente.faturamento }}</td>
                <td class="text-center">
                    <button type="button"
                            class="btn btn-default btn-xs"
                            ng-click="goToDocumentos(cliente.id_contrato)">
                        <i class="fa fa-file" aria-hidden="true"></i>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>

</div>