<div class="modal" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" style="width:80%;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    {{documento.id ? 'Atualizar documento' : 'Cadastrar documento'}}
                </h4>
                <button type="button" ng-click="cerrar('cancel')" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <div alert-bootstrap></div>
                        <div loading-bootstrap></div>
                    </div>
                </div>
                <form name="formDocumento" ng-submit="salvarDocumento()" novalidate>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <div class="input-group" id="documento">
                                <span class="input-group-btn">
                                      <span class="btn btn-default btn-file">
                                           {{documento.arquivo ? ( documento.arquivo.name | limitTo: 15 ) + '...' : 'Anexar...' }}
                                          <input ngf-select
                                                 type="file"
                                                 ngf-pattern="'application/pdf'"
                                                 ngf-keep="true"
                                                 ng-model="documento.arquivo"
                                                 ng-required="documento.id ? false : true"
                                          >
                                      </span>
                                </span>
                                <select class="selectBootstrap form-control"
                                        id="tipoDocumento"
                                        name="tipoDocumento"
                                        ng-options="tipoDocumento as tipoDocumento.nome for tipoDocumento in listaDocumentos track by tipoDocumento.id"
                                        ng-model="documento.id_tipo_documento"
                                        ng-required="true">
                                    <option value="">Escolha o tipo de documento...</option>
                                </select>

                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button"
                                class="btn btn-danger"
                                ng-click="cerrar('cancel')"
                                data-dismiss="modal">Cancelar
                        </button>
                        <button type="submit"
                                ng-disabled="formDocumento.$invalid"
                                class="btn btn-success">{{!documento.id ? 'Enviar' : 'Atualizar'}}
                        </button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
