<div class="col-sm-12" ng-controller="documentoClienteController" ng-cloak>
    <h4>Documentos</h4>
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div alert-bootstrap></div>
            <div loading-bootstrap></div>
        </div>
    </div>
    <div class="pull-right">
        <form class="form-inline">
            <div class="form-group">
                <label for="cmpFilter">Pesquisar</label>
                <input type="text"
                       id="cmpFilter"
                       name="cmpFilter"
                       class="form-group"
                       ng-model="filter">
            </div>
            <button type="button"
                    class="btn btn-success btn-sm"
                    ng-click="showEditModal()">
                <i class="glyphicon glyphicon-plus"></i>
                <strong>Anexar Documento</strong>
            </button>
        </form>
    </div>
    <table class="table table-hover" ng-if="listaDocumentos.length">
        <thead>
        <tr>
            <th class="text-center">Cliente</th>
            <th class="text-center">Documento</th>
            <th class="text-center">Ações</th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="documento in listaDocumentos">
            <td class="text-center">{{documento.cliente}}</td>
            <td class="text-center">{{documento.tipo_documento}}</td>
            <td class="text-center">
                <button type="button"
                        class="btn btn-default btn-xs"
                        ng-click="visualizar(documento)">
                    <i class="fa fa-download" aria-hidden="true"></i>
                </button>
                <button type="button"
                        class="btn btn-default btn-xs"
                        ng-click="showModalDocumentos(documento.id_contrato)">
                    <i class="fa fa-edit" aria-hidden="true"></i>
                </button>
            </td>
        </tr>
        </tbody>
    </table>

</div>
<!--
<h4>Documento do Cliente</h4>
<div class="form-group col-md-12">
    <form>
        <div class="form-group col-md-3">
            <label for="cliente">Cliente</label>
            <select class="form-control">
                <option>Pablo</option>
                <option>Santos</option>
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="tipo_documento">Tipo de Documento</label>
            <select class="form-control">
                <option>Cadastro</option>
                <option>Fiscal - PGDAS</option>
            </select>
        </div>
        <div class="form-group col-md-3">
            <label for="exampleInputFile">Arquivo</label>
            <input type="file"
                   id="exampleInputFile"
                   ngf-select
                   ngf-accept="'image/*'"
                   ngf-keep="true"
            >
        </div>
        <button type="button" class="btn btn-primary">Adicionar</button>
    </form>
</div>
-->