<?php
if (!defined('ABSPATH') || !$this instanceof \MocaBonita\view\MbView) :
    die("Você não tem permissão para acessar este arquivo!");
endif;
?>

<!--https://www.sourcecodester.com/tutorials/javascript/11921/angularjs-login-session-using-phpmysqli.html-->
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<style>
    #login .container #login-row #login-column #login-box {
        margin-top: 20px;
        max-width: 600px;
        height: 320px;
        border: 1px solid #9C9C9C;
        background-color: #EAEAEA;
    }
    #login .container #login-row #login-column #login-box #login-form {
        padding: 20px;
    }
    #login .container #login-row #login-column #login-box #login-form #register-link {
        margin-top: -20px;
    }
</style>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div alert-bootstrap></div>
        <div loading-bootstrap></div>
    </div>
</div>
<!--
<div class="col-sm-5 col-sm-offset-1">
    <form name="formDadosLogin"
          method="post"
          ng-submit="logar()"
          autocomplete="off"
          novalidate>

            <div class="form-group">
                <label for="cpf">CPF:(*)</label>
            <input type="text"
                   ng-model="formLogin.login"
                   class="form-control"
                   id="login"
                   ng-required="true"
                   placeholder="CPF"/>
        </div>


        <div class="form-group">
            <label for="senha">Senha:(*)</label>
            <input type="password"
                   ng-model="formLogin.senha"
                   class="form-control"
                   id="senha"
                   ng-required="true"
                   placeholder="Senha"/>
        </div>

        <div class="form-group col-sm-12 text-center">
            <button class="btn btn-success btn-sm"
                    type="submit"
                    ng-disabled="formDadosLogin.$error.required || formDadosLogin.$invalid ">
                Entrar
            </button>

        </div>

    </form>

</div>
-->

<div class="container">
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">Login</div>
                <!--<div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>-->
            </div>

            <div style="padding-top:30px" class="panel-body" >

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                <form id="formDadosLogin" name="formDadosLogin" class="form-horizontal" role="form" method="post"
                      ng-submit="logar()"
                      autocomplete="off"
                      novalidate>

                    <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id="login-username"
                               type="text"
                               class="form-control"
                               name="cpf"
                               ng-model="formLogin.login"
                               placeholder="CPF/CNPJ">
                    </div>

                    <div style="margin-bottom: 25px" class="input-group" >
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input id="login-password"
                               type="password"
                               class="form-control"
                               name="senha"
                               ng-model="formLogin.senha"
                               placeholder="Senha">

                    </div>
                    <!--
                    <div class="input-group">
                        <div class="checkbox">
                            <label>
                                <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                            </label>
                        </div>
                    </div>
                     -->

                    <div style="margin-top:10px" class="form-group">
                        <!-- Button -->
                        <div class="col-sm-12 controls">
                            <button class="btn btn-success"
                                    type="submit"
                                    ng-disabled="formDadosLogin.$error.required || formDadosLogin.$invalid ">
                                Entrar
                            </button>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-12 control">
                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                Ainda não tem cadastro?
                                <a href="http://www.rsccontabilidade.com.br/?page_id=5202/#!/cadastro">
                                    Cadastre-se
                                </a>
                            </div>
                        </div>
                    </div>
                </form>



            </div>
        </div>
    </div>
