<?php
if (!defined('ABSPATH') || !$this instanceof \MocaBonita\view\MbView) :
    die("Você não tem permissão para acessar este arquivo!");
endif;
?>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div alert-bootstrap></div>
        <div loading-bootstrap></div>
    </div>
</div>

<div class="col-sm-5 col-sm-offset-1">
    <form name="formDadosLogin"
          method="post"
          ng-submit="logar()"
          autocomplete="off"
          novalidate>

            <div class="form-group">
                <label for="cpf">CPF:(*)</label>
            <input type="text"
                   ng-model="formLogin.login"
                   class="form-control"
                   id="login"
                   ng-required="true"
                   placeholder="CPF"/>
        </div>


        <div class="form-group">
            <label for="senha">Senha:(*)</label>
            <input type="password"
                   ng-model="formLogin.senha"
                   class="form-control"
                   id="senha"
                   ng-required="true"
                   placeholder="Senha"/>
        </div>

        <div class="form-group col-sm-12 text-center">
            <button class="btn btn-success btn-sm"
                    type="submit"
                    ng-disabled="formDadosLogin.$error.required || formDadosLogin.$invalid ">
                Entrar
            </button>
            <button class="btn btn-success btn-sm"
                    ng-click="redirecionar('/cadastro')"
                    type="button">
                Cadastre-se
            </button>


        </div>

    </form>

</div>

