
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css"
      rel="stylesheet">

<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">Área do Cliente</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <!--
                <li class="dropdown">
                    <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"><i
                                class="fa fa-user-circle"></i> {{dadosUsuario.nome}} <span class="caret"></span></a>
                    <ul id="g-account-menu" class="dropdown-menu" role="menu">
                        <li><a href="#"><i class="fa fa-user-secret"></i> My Profile</a></li>
                    </ul>
                </li>
                -->
                <li><a href="#" ng-click="sair()"><i class="fa fa-sign-out"></i> Sair</a></li>
            </ul>
        </div>
    </div>
    <!-- /container -->
</div>

<!-- /Header -->

<!-- Main -->

<div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">

    <ul class="nav nav-pills nav-stacked" style="border-right:1px solid black">
        <!--<li class="nav-header"></li>-->
        <li><a href=""><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="" ng-click="abrirDadosPessoais()"><i class="fa fa-address-card"></i> Dados Pessoais</a></li>
        <li><a href="" ng-click="abrirPagamentos()"><i class="fa fa-money"></i> Pagamentos</a></li>
        <li><a href="" ng-click=""><i class="fa fa-file"></i> Documentos</a></li>
        <li><a href="" ng-click="abrirBoletos()"><i class="fa fa-barcode"></i> Boletos</a></li>
        <li><a href="" ng-click="abrirAssinatura()"><i class="fa fa-handshake-o"></i> Assinatura</a></li>

    </ul>
</div><!-- /span-3 -->
<div class="col-lg-10 col-md-10 col-sm-9 col-xs-12">
    <!-- Right -->
    <!--<a href="#"><strong><span class="fa fa-dashboard"></span> My Dashboard</strong></a>-->
    <hr>
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            <div alert-bootstrap></div>
            <div loading-bootstrap></div>
        </div>
    </div>

    <div class="col-sm-10 col-sm-offset-1" ng-if="formCliente">
        <form name="formDadosCliente"
              method="post"
              ng-submit="atualizarCliente()"
              autocomplete="off"
              novalidate>

            <h5 class="page-header">Dados do Cliente</h5>
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="nome">Nome Completo:(*)</label>
                    <input type="nome"
                           ng-model="formCliente.nome"
                           class="form-control"
                           id="nome"
                           placeholder="Nome"/>
                </div>
                <div class="form-group col-md-3">
                    <label for="data_nascimento">Data de Nascimento:(*)</label>
                    <input id="data_nascimento"
                           ng-init="tratarData(formCliente)"
                           ng-model="formCliente.data_nascimento"
                           class="form-control"
                           type="text"
                           ui-date-mask="DD/MM/YYYY"
                           placeholder="Data de Nascimento"
                    />
                </div>
                <div class="form-group col-md-3">
                    <label for="genero">Gênero:(*)</label>
                    <select name="genero"
                            id="genero"
                            ng-model="formCliente.id_sexo"
                            ng-options="genero as genero.nome for genero in listaGeneros track by genero.id"
                            ng-required="true"
                            class="form-control">
                    </select>

                </div>
                <div class="form-group col-md-3">
                    <label for="estado_civil">Estado Civil:(*)</label>
                    <select name="estado_civil"
                            id="estado_civil"
                            ng-model="formCliente.id_estado_civil"
                            ng-options="estadocivil as estadocivil.nome for estadocivil in listaEstadosCivis track by estadocivil.id"
                            ng-required="true"
                            class="form-control">
                    </select>
                </div>
            </div>


            <h5 class="page-header">Documentos</h5>
            <div class="row">


                <div class="radio-inline">
                    <label>
                        <input type="radio" ng-model="formCliente.id_tipo_pessoa" ng-disabled="!formCliente.id_tipo_pessoa" ng-value="'1'" name="tipo">Pessoa Física
                    </label>
                </div>
                <div class="radio-inline">
                    <label>
                        <input type="radio" ng-model="formCliente.id_tipo_pessoa" ng-disabled="!formCliente.id_tipo_pessoa" ng-value="'2'" name="tipo">Pessoa Jurídica
                    </label>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-3" ng-if="fisica==true || formCliente.id_tipo_pessoa == 1 ">
                    <label for="cpf_cnpj">CPF:(*)</label>
                    <input type="text"
                           ng-model="formCliente.cpf"
                           class="form-control"
                           id="cpf"
                           ng-cpf
                           ui-br-cpf-mask
                           ng-required="true"
                           placeholder="CPF"/>
                    <p ng-show="formCliente.cpf.$invalid && !formCliente.cpf.$pristine" class="help-block">O seu CPF está inválido!</p>
                </div>
                <div class="form-group col-md-3" ng-if="fisica==false || formCliente.id_tipo_pessoa == 2">
                    <label for="cnpj">CNPJ:(*)</label>
                    <input type="text"
                           ng-model="formCliente.cnpj"
                           name="cnpj"
                           class="form-control"
                           id="cnpj"
                           ng-cnpj
                           ui-br-cnpj-mask
                           ng-required="true"
                           placeholder="CNPJ"/>
                    <p style="color:red" ng-show ="formDadosCliente.cnpj.$invalid && !formDadosCliente.cnpj.$pristine">O seu CNPJ está inválido!</p>
                </div>
                <div class="form-group col-md-3">
                    <label for="rg">RG:(*)</label>
                    <input type="text"
                           ng-model="formCliente.rg"
                           class="form-control"
                           id="rg"
                           numeric-only
                           ng-required="true"
                           placeholder="RG"/>
                </div>
                <div class="form-group col-md-3">
                    <label for="orgaoExpedidor">Órgão Emissor:(*)</label>
                    <input type="text"
                           ng-model="formCliente.orgao_rg"
                           class="form-control"
                           id="orgaoExpedidor"
                           ng-required="true"
                           placeholder="Órgão Expedidor"/>
                </div>
                <div class="form-group col-md-3">
                    <label for="dataEmissao">Data de Emissão:(*)</label>
                    <input type="text"
                           ng-model="formCliente.data_emissao_rg"
                           class="form-control"
                           id="dataEmissao"
                           ng-required="true"
                           ui-date-mask="DD/MM/YYYY"
                           placeholder="Data de Emissão"/>
                </div>
            </div>
            <h5 class="page-header">Endereço</h5>
            <div class="row">
                <div class="form-group col-md-3">
                    <label for="cep">CEP:(*)</label>
                    <input type="text"
                           ng-model="formCliente.cep"
                           class="form-control"
                           id="cep"
                           ng-required="true"
                           ng-blur="buscarCep(formCliente)"
                           placeholder="CEP"/>
                </div>

                <div class="form-group col-md-4">
                    <label for="rua">Rua:(*)</label>
                    <input type="text"
                           ng-model="formCliente.rua"
                           class="form-control"
                           id="rua"
                           ng-required="true"
                           placeholder="Rua"/>
                </div>

                <div class="form-group col-md-3">
                    <label for="numero">Número:(*)</label>
                    <input type="text"
                           ng-model="formCliente.numero"
                           class="form-control"
                           id="numero"
                           ng-required="true"
                           placeholder="Número"/>
                </div>

                <div class="form-group col-md-4">
                    <label for="complemento">Complemento:(*)</label>
                    <input type="text"
                           ng-model="formCliente.complemento"
                           class="form-control"
                           id="complemento"
                           ng-required="true"
                           placeholder="Complemento"/>
                </div>

                <div class="form-group col-md-3">
                    <label for="bairro">Bairro:</label>
                    <input type="text"
                           ng-model="formCliente.bairro"
                           class="form-control"
                           id="bairro"
                           placeholder="Bairro"/>
                </div>

                <div class="form-group col-md-3">
                    <label for="cidade">Cidade:(*)</label>
                    <input type="text"
                           ng-model="formCliente.cidade"
                           class="form-control"
                           id="cidade"
                           ng-required="true"
                           placeholder="Cidade"/>
                </div>

                <div class="form-group col-md-3">
                    <label for="estado">Estado:</label>
                    <input type="text"
                           ng-model="formCliente.estado"
                           class="form-control"
                           id="estado"
                           placeholder="Estado"/>
                </div>
            </div>

            <h5 class="page-header">Contato</h5>
            <div class="row">
                <div class="form-group col-md-2">
                    <label for="ddd">DDD:</label>
                    <input type="text"
                           ng-model="formCliente.ddd"
                           class="form-control"
                           id="ddd"
                           placeholder="DDD"/>
                </div>

                <div class="form-group col-md-3">
                    <label for="telefoneResidencial">Telefone Residencial:</label>
                    <input type="text"
                           ng-model="formCliente.telefone_residencial"
                           class="form-control"
                           id="telefoneResidencial"
                           placeholder="Telefone Residencial"/>
                </div>

                <div class="form-group col-md-3">
                    <label for="telefoneCelular">Telefone Celular:(*)</label>
                    <input type="text"
                           ng-blur="tratarData(formCliente)"
                           ng-model="formCliente.telefone_celular"
                           class="form-control"
                           id="telefoneCelular"
                           ng-required="true"
                           placeholder="Telefone Celular"/>
                </div>

                <div class="form-group col-md-4">
                    <label for="email">E-mail:(*)</label>
                    <input type="email"
                           ng-model="formCliente.email"
                           class="form-control"
                           id="email"
                           ng-required="true"
                           placeholder="Email"/>
                </div>
            </div>

            <div class="form-group col-sm-12 text-center">
                <button class="btn btn-success btn-sm"
                        type="submit"
                        ng-disabled="formDadosCliente.$error.required || formDadosCliente.$invalid ">
                    Alterar
                </button>


            </div>

        </form>
    </div>

    <div class="col-sm-10 col-sm-offset-1" ng-if="listaTransacoes">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
            <tr>
                <th>Plano</th>
                <th>Valor</th>
                <th>Forma de Pagamento</th>
                <th>Pago Em</th>
                <th>Status</th>

            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="transacao in listaTransacoes">
                <td>{{transacao.tipo_empresa}}</td>
                <td class="center">R$ {{transacao.valor}}</td>
                <td class="center">{{transacao.forma_pagamento}}</td>
                <td class="center">{{transacao.data_transacao | date:'dd/MM/yyyy HH:mm:ss' }}</td>
                <td class="center">{{transacao.status}}</td>
            </tr>
            <tr class="animate-repeat" ng-if="listaTransacoes.length == 0">
                <td colspan="8" class="text-center">
                    <em>
                        Nenhum resultado foi encontrado.
                    </em>
                </td>
            </tr>
            </tbody>
        </table>

    </div>

    <div class="col-sm-10 col-sm-offset-1" ng-if="listaBoletos">
        <table width="100%" class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Código de Barras</th>
                <th>Valor</th>
                <th>Data de Vencimento</th>
                <th>Geração</th>

            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="boleto in listaBoletos">
                <td>{{boleto.codigo_barras}}</td>
                <td class="center">R$ {{boleto.valor}}</td>
                <td class="center">{{boleto.data_vencimento | date:'dd/MM/yyyy' }}</td>
                <td class="text-center">
                    <a class="btn btn-danger btn-sm" href="{{boleto.link}}" target="_blank">
                        <span class="glyphicon glyphicon-barcode" aria-hidden="true"></span>
                    </a>
                </td>
            </tr>
            <tr class="animate-repeat" ng-if="listaBoletos.length == 0">
                <td colspan="8" class="text-center">
                    <em>
                        Nenhum resultado foi encontrado.
                    </em>
                </td>
            </tr>
            </tbody>
        </table>

    </div>

    <div class="col-sm-10 col-sm-offset-1" ng-if="listaAssinaturas">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Plano</th>
                <th>Valor</th>
                <th>Faturamento</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="assinatura in listaAssinaturas">
                <td>{{assinatura.tipo_empresa}}</td>
                <td class="center">R$ {{assinatura.valor}}</td>
                <td class="center">{{assinatura.faturamento}}</td>
                <td class="center">{{assinatura.status}}</td>
                <td class="text-center">
                    <a class="btn btn-danger btn-sm" ng-click="cancelarAssinatura(contrato)">
                        Cancelar
                    </a>
                    <!--
                    <a class="btn btn-info btn-sm" ng-click="renovarAssinatura(contrato)">
                        Renovar
                    </a>
                    -->
                </td>
            </tr>
            <tr class="animate-repeat" ng-if="listaAssinaturas.length == 0">
                <td colspan="8" class="text-center">
                    <em>
                        Nenhum resultado foi encontrado.
                    </em>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
</div>
